### ISSUE TITLE
Breaks homescreen default

### ISSUE THREAD

**Issue by StickyDigit** [VirtCode/SmartMouse#15] opened 2024-02-16 17:05 UTC
When this app is installed, my home-screen selection will not 'stick' any more.

To clarify: My home-screen on two devices is Trebuchet, and that is set as default, but I have a couple of other options installed. Normally, I hit home and trebuchet is where I end up. With SmartMouse installed, every time I hit 'home' I get asked which home-screen to use, regardless whether I click 'every time'. Uninstalling the app resolves the issue.

LineageOS 18.1 on two different devices, one with Gapps, one without.

**Comment by VirtCode** [comment] 2024-02-17 10:29
hmm that's very odd

My first guess would be that it is in some way related to this app *trying* to suppress the home, back, etc. buttons when in mouse view to prevent accidental touches. But that doesn't explain at all why it is also happening when leaving other apps...
I'll remove that some time soon anyways, as it does not really work / is practically impossible to do on most modern android versions. So we'll see whether that fixes it.

I'll keep this open until then as this is far from intended behavior and seems really annoying. Also, if anyone else has a hunch on what else could cause this behavior, let me know!

**Comment by nate-moo** [comment] 2024-03-27 09:16
Can confirm this is an issue, and Nova launcher is actually what alerted me to this bug and this app. 

I can test things if needed and/or provide specific logs if desired.

**Comment by VirtCode** [comment] 2024-03-28 11:47
Thanks for the hint, I can also reproduce the issue with the nova launcher! I think I have also found the issue, which was an unneeded intent category which was left over from some time ago. I've removed that in the latest commit (https://github.com/VirtCode/SmartMouse/commit/897628c0df4d50abfe2c9140676e71153cbaf26e) and that fixes it for me.

I'd be glad if you could test this on your end, and also if someone could test this on LineageOS. I'll upload a build here tomorrow (when I have access to my signature keys), so you don't have to try build it yourself.

**Comment by VirtCode** [comment] 2024-03-29 10:28
Here's a build of that commit. I'd be glad if someone could test this especially on LineageOS.
The build is in a zip because GitHub won't let me upload an apk: [SmartMouse-897628c-launcher-fix.zip](https://github.com/VirtCode/SmartMouse/files/14802801/SmartMouse-897628c-launcher-fix.zip)

**Comment by StickyDigit** [comment] 2024-03-29 13:11
That's working for e on the LineageOS device I raised the issue for.

**Comment by VirtCode** [comment] 2024-03-29 14:06
That's great, thanks for testing! I'll close this then.

**Closed by VirtCode** 2024-03-29 14:06 UTC
Labels: bug
